stack: hyperspace
version: 0.1.2
description: Hyperspace App 
variables:
  app_domain:
    type: string
    default: app.hypeisreal.com
    from:
      prompt: App domain
expose: loadbalancer
services:
  loadbalancer:
    image: kontena/lb:latest
    ports:
      - 80:80
  app:
    image: jatula/hyperspace:0.1
    instances: 3
    links:
      - loadbalancer
    environment:
      - KONTENA_LB_INTERNAL_PORT=9393
      - KONTENA_LB_VIRTUAL_HOSTS={{ app_domain }}
    deploy:
      strategy: ha
      wait_for_port: 9393