#!/bin/bash
set -eu

runner_name=${1}
runner_host=${2}
runner_token=${3}
runner_image=${4}
runner_dnsname=${5}

export DEBIAN_FRONTEND=noninteractive

##Wait for Gitlab instance to come online
sleep 90

## Install docker
curl -sSL https://get.docker.com/ | sh
usermod -aG docker ubuntu

## Write out CA cert
openssl s_client -connect ${runner_dnsname}:443 -showcerts < /dev/null | openssl x509 -outform PEM > /etc/gitlab-runner/certs/ca.crt

## Install GitLab Multi-Runner
curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | bash
apt-get install gitlab-ci-multi-runner
# Configure runner
gitlab-ci-multi-runner register \
  --non-interactive \
  --url ${runner_host} \
  --registration-token ${runner_token} \
  --name ${runner_name} \
  --executor docker \
  --tls-ca-file /etc/gitlab-runner/certs/ca.crt \
  --docker-image ${runner_image} 2>&1 >> /var/log/gitlab-ci-multi-runner.boostrap.log
